export interface GameEntry {
  slug: string;
  nameEn: string;
  nameTh: string;
  nameShort: string;
  gen: number;
  year: number;
  platform: string;
  region: string;
  regionTh: string;
  mechanic: string;
  mechanicTh: string;
  color1: string;
  color2: string;
  icon: string;
  starters: number[]; // PokeAPI IDs
  mascots: number[];  // box legendaries
  smogonFormat?: string;
  totalPokemon: number;
}

export const GAMES: GameEntry[] = [
  // ─── Generation 9 ─────────────────────────────────────────────
  {
    slug: "scarlet-violet",
    nameEn: "Scarlet & Violet",
    nameTh: "สการ์เลต & ไวโอเลต",
    nameShort: "SV",
    gen: 9,
    year: 2022,
    platform: "Switch",
    region: "Paldea",
    regionTh: "ปัลเดีย",
    mechanic: "Terastal",
    mechanicTh: "เทราสทัล",
    color1: "#c0392b",
    color2: "#6c3483",
    icon: "🔴",
    starters: [906, 909, 912],
    mascots: [1007, 1008],
    smogonFormat: "gen9ou",
    totalPokemon: 400,
  },
  {
    slug: "legends-arceus",
    nameEn: "Legends: Arceus",
    nameTh: "เลเจนด์ส: อาร์เซอุส",
    nameShort: "PLA",
    gen: 8,
    year: 2022,
    platform: "Switch",
    region: "Hisui",
    regionTh: "ฮิซุอิ",
    mechanic: "Alpha Pokémon",
    mechanicTh: "อัลฟา โปเกมอน",
    color1: "#1a5276",
    color2: "#d4ac0d",
    icon: "🌕",
    starters: [722, 155, 501],
    mascots: [493],
    totalPokemon: 242,
  },

  // ─── Generation 8 ─────────────────────────────────────────────
  {
    slug: "sword-shield",
    nameEn: "Sword & Shield",
    nameTh: "ซอร์ด & ชีลด์",
    nameShort: "SwSh",
    gen: 8,
    year: 2019,
    platform: "Switch",
    region: "Galar",
    regionTh: "กาล่า",
    mechanic: "Dynamax",
    mechanicTh: "ไดนาแมกซ์",
    color1: "#2874a6",
    color2: "#922b21",
    icon: "⚔️",
    starters: [810, 813, 816],
    mascots: [888, 889],
    smogonFormat: "gen8ou",
    totalPokemon: 400,
  },
  {
    slug: "bdsp",
    nameEn: "Brilliant Diamond & Shining Pearl",
    nameTh: "บริลเลียนต์ ไดมอนด์ & ชายนิ่ง เพิร์ล",
    nameShort: "BDSP",
    gen: 4,
    year: 2021,
    platform: "Switch",
    region: "Sinnoh",
    regionTh: "ซินโนห์",
    mechanic: "Underground",
    mechanicTh: "แกรนด์ อันเดอร์กราวด์",
    color1: "#5c8fd6",
    color2: "#e8b4c8",
    icon: "💎",
    starters: [387, 390, 393],
    mascots: [483, 484],
    totalPokemon: 493,
  },

  // ─── Generation 7 ─────────────────────────────────────────────
  {
    slug: "ultra-sun-moon",
    nameEn: "Ultra Sun & Ultra Moon",
    nameTh: "อัลตร้า ซัน & อัลตร้า มูน",
    nameShort: "USUM",
    gen: 7,
    year: 2017,
    platform: "3DS",
    region: "Alola",
    regionTh: "อาโลล่า",
    mechanic: "Z-Moves",
    mechanicTh: "Z-มูฟ",
    color1: "#d68910",
    color2: "#7d3c98",
    icon: "🌟",
    starters: [722, 725, 728],
    mascots: [800],
    smogonFormat: "gen7ou",
    totalPokemon: 807,
  },
  {
    slug: "sun-moon",
    nameEn: "Sun & Moon",
    nameTh: "ซัน & มูน",
    nameShort: "SM",
    gen: 7,
    year: 2016,
    platform: "3DS",
    region: "Alola",
    regionTh: "อาโลล่า",
    mechanic: "Z-Moves",
    mechanicTh: "Z-มูฟ",
    color1: "#f39c12",
    color2: "#6c3483",
    icon: "☀️",
    starters: [722, 725, 728],
    mascots: [791, 792],
    totalPokemon: 802,
  },

  // ─── Generation 6 ─────────────────────────────────────────────
  {
    slug: "oras",
    nameEn: "Omega Ruby & Alpha Sapphire",
    nameTh: "โอเมก้า รูบี้ & อัลฟา แซปฟิร์",
    nameShort: "ORAS",
    gen: 3,
    year: 2014,
    platform: "3DS",
    region: "Hoenn",
    regionTh: "ฮออนน์",
    mechanic: "Mega Evolution",
    mechanicTh: "เมก้าอีโวลูชั่น",
    color1: "#c0392b",
    color2: "#1a5276",
    icon: "🌊",
    starters: [252, 255, 258],
    mascots: [383, 382],
    smogonFormat: "gen6ou",
    totalPokemon: 721,
  },
  {
    slug: "x-y",
    nameEn: "X & Y",
    nameTh: "X & Y",
    nameShort: "XY",
    gen: 6,
    year: 2013,
    platform: "3DS",
    region: "Kalos",
    regionTh: "กาลอส",
    mechanic: "Mega Evolution",
    mechanicTh: "เมก้าอีโวลูชั่น",
    color1: "#2471a3",
    color2: "#922b21",
    icon: "🔷",
    starters: [650, 653, 656],
    mascots: [716, 717],
    smogonFormat: "gen6ou",
    totalPokemon: 721,
  },

  // ─── Generation 5 ─────────────────────────────────────────────
  {
    slug: "black2-white2",
    nameEn: "Black 2 & White 2",
    nameTh: "แบล็ก 2 & ไวต์ 2",
    nameShort: "B2W2",
    gen: 5,
    year: 2012,
    platform: "DS",
    region: "Unova",
    regionTh: "อูโนว่า",
    mechanic: "PWT",
    mechanicTh: "Pokemon World Tournament",
    color1: "#1a1a2e",
    color2: "#e0e0e0",
    icon: "🌀",
    starters: [495, 498, 501],
    mascots: [646, 646],
    smogonFormat: "gen5ou",
    totalPokemon: 649,
  },
  {
    slug: "black-white",
    nameEn: "Black & White",
    nameTh: "แบล็ก & ไวต์",
    nameShort: "BW",
    gen: 5,
    year: 2010,
    platform: "DS",
    region: "Unova",
    regionTh: "อูโนว่า",
    mechanic: "Triple/Rotation",
    mechanicTh: "ทริปเปิล/โรเตชั่น",
    color1: "#2c3e50",
    color2: "#bdc3c7",
    icon: "⬛",
    starters: [495, 498, 501],
    mascots: [643, 644],
    totalPokemon: 649,
  },

  // ─── Generation 4 ─────────────────────────────────────────────
  {
    slug: "hgss",
    nameEn: "HeartGold & SoulSilver",
    nameTh: "ฮาร์ตโกลด์ & โซลซิลเวอร์",
    nameShort: "HGSS",
    gen: 2,
    year: 2009,
    platform: "DS",
    region: "Johto",
    regionTh: "โจโตะ",
    mechanic: "Pokéathlon",
    mechanicTh: "โปเกแอทลีต",
    color1: "#d4ac0d",
    color2: "#bdc3c7",
    icon: "🏅",
    starters: [152, 155, 158],
    mascots: [250, 249],
    totalPokemon: 493,
  },
  {
    slug: "platinum",
    nameEn: "Platinum",
    nameTh: "แพลตินัม",
    nameShort: "Pt",
    gen: 4,
    year: 2008,
    platform: "DS",
    region: "Sinnoh",
    regionTh: "ซินโนห์",
    mechanic: "Distortion World",
    mechanicTh: "Distortion World",
    color1: "#717d7e",
    color2: "#2e4057",
    icon: "⭐",
    starters: [387, 390, 393],
    mascots: [487],
    smogonFormat: "gen4ou",
    totalPokemon: 493,
  },
  {
    slug: "diamond-pearl",
    nameEn: "Diamond & Pearl",
    nameTh: "ไดมอนด์ & เพิร์ล",
    nameShort: "DPPt",
    gen: 4,
    year: 2006,
    platform: "DS",
    region: "Sinnoh",
    regionTh: "ซินโนห์",
    mechanic: "Underground",
    mechanicTh: "อันเดอร์กราวด์",
    color1: "#5d6d7e",
    color2: "#d7bde2",
    icon: "🔮",
    starters: [387, 390, 393],
    mascots: [483, 484],
    totalPokemon: 493,
  },

  // ─── Generation 3 ─────────────────────────────────────────────
  {
    slug: "emerald",
    nameEn: "Emerald",
    nameTh: "เอเมอรัลด์",
    nameShort: "E",
    gen: 3,
    year: 2004,
    platform: "GBA",
    region: "Hoenn",
    regionTh: "ฮออนน์",
    mechanic: "Battle Frontier",
    mechanicTh: "แบทเทิล ฟรอนเทียร์",
    color1: "#1e8449",
    color2: "#148f77",
    icon: "💚",
    starters: [252, 255, 258],
    mascots: [384],
    smogonFormat: "gen3ou",
    totalPokemon: 386,
  },
  {
    slug: "ruby-sapphire",
    nameEn: "Ruby & Sapphire",
    nameTh: "รูบี้ & แซปฟิร์",
    nameShort: "RSE",
    gen: 3,
    year: 2002,
    platform: "GBA",
    region: "Hoenn",
    regionTh: "ฮออนน์",
    mechanic: "Abilities & Nature",
    mechanicTh: "Ability และ Nature",
    color1: "#c0392b",
    color2: "#1a5276",
    icon: "❤️",
    starters: [252, 255, 258],
    mascots: [383, 382],
    totalPokemon: 386,
  },
  {
    slug: "frlg",
    nameEn: "FireRed & LeafGreen",
    nameTh: "ไฟร์เรด & ลีฟกรีน",
    nameShort: "FRLG",
    gen: 1,
    year: 2004,
    platform: "GBA",
    region: "Kanto",
    regionTh: "คันโตะ",
    mechanic: "National Dex",
    mechanicTh: "National Dex",
    color1: "#e74c3c",
    color2: "#27ae60",
    icon: "🔥",
    starters: [1, 4, 7],
    mascots: [150],
    totalPokemon: 386,
  },

  // ─── Generation 2 ─────────────────────────────────────────────
  {
    slug: "crystal",
    nameEn: "Crystal",
    nameTh: "คริสตัล",
    nameShort: "Crystal",
    gen: 2,
    year: 2000,
    platform: "GBC",
    region: "Johto",
    regionTh: "โจโตะ",
    mechanic: "Battle Tower",
    mechanicTh: "แบทเทิล ทาวเวอร์",
    color1: "#5dade2",
    color2: "#2471a3",
    icon: "💎",
    starters: [152, 155, 158],
    mascots: [245],
    totalPokemon: 251,
  },
  {
    slug: "gold-silver",
    nameEn: "Gold & Silver",
    nameTh: "โกลด์ & ซิลเวอร์",
    nameShort: "GSC",
    gen: 2,
    year: 1999,
    platform: "GBC",
    region: "Johto",
    regionTh: "โจโตะ",
    mechanic: "Day & Night",
    mechanicTh: "กลางวัน/กลางคืน",
    color1: "#d4ac0d",
    color2: "#aab7b8",
    icon: "🥇",
    starters: [152, 155, 158],
    mascots: [250, 249],
    totalPokemon: 251,
  },

  // ─── Generation 1 ─────────────────────────────────────────────
  {
    slug: "yellow",
    nameEn: "Yellow",
    nameTh: "เยลโลว์",
    nameShort: "Yellow",
    gen: 1,
    year: 1998,
    platform: "GB",
    region: "Kanto",
    regionTh: "คันโตะ",
    mechanic: "Pikachu Follows",
    mechanicTh: "พิคาชูเดินตาม",
    color1: "#f4d03f",
    color2: "#e67e22",
    icon: "⚡",
    starters: [25],
    mascots: [150],
    totalPokemon: 151,
  },
  {
    slug: "red-blue",
    nameEn: "Red & Blue",
    nameTh: "เรด & บลู",
    nameShort: "RBY",
    gen: 1,
    year: 1996,
    platform: "GB",
    region: "Kanto",
    regionTh: "คันโตะ",
    mechanic: "The Original",
    mechanicTh: "ต้นกำเนิด Pokémon",
    color1: "#e74c3c",
    color2: "#2874a6",
    icon: "🎮",
    starters: [1, 4, 7],
    mascots: [150, 151],
    smogonFormat: "gen1ou",
    totalPokemon: 151,
  },
];

export const GAMES_BY_GEN: Record<number, GameEntry[]> = GAMES.reduce(
  (acc, game) => {
    const key = game.gen;
    if (!acc[key]) acc[key] = [];
    acc[key].push(game);
    return acc;
  },
  {} as Record<number, GameEntry[]>
);

// Gen descriptions
export const GEN_INFO: Record<number, { label: string; years: string; platform: string }> = {
  9: { label: "Generation 9", years: "2022–ปัจจุบัน", platform: "Nintendo Switch" },
  8: { label: "Generation 8", years: "2019–2022", platform: "Nintendo Switch" },
  7: { label: "Generation 7", years: "2016–2017", platform: "Nintendo 3DS" },
  6: { label: "Generation 6", years: "2013–2014", platform: "Nintendo 3DS" },
  5: { label: "Generation 5", years: "2010–2012", platform: "Nintendo DS" },
  4: { label: "Generation 4", years: "2006–2009", platform: "Nintendo DS" },
  3: { label: "Generation 3", years: "2002–2004", platform: "Game Boy Advance" },
  2: { label: "Generation 2", years: "1999–2001", platform: "Game Boy Color" },
  1: { label: "Generation 1", years: "1996–1998", platform: "Game Boy" },
};

export const PLATFORM_COLORS: Record<string, string> = {
  "Switch": "text-red-400 bg-red-400/10",
  "3DS": "text-blue-400 bg-blue-400/10",
  "DS": "text-yellow-400 bg-yellow-400/10",
  "GBA": "text-purple-400 bg-purple-400/10",
  "GBC": "text-green-400 bg-green-400/10",
  "GB": "text-gray-400 bg-gray-400/10",
  "Mobile": "text-green-400 bg-green-400/10",
  "Mobile/Switch": "text-cyan-400 bg-cyan-400/10",
  "Switch/Mobile": "text-yellow-400 bg-yellow-400/10",
};

// ─── Platform / Spin-off Games ─────────────────────────────────────────────────
export interface PlatformGame {
  slug: string;
  nameEn: string;
  nameTh: string;
  nameShort: string;
  platform: string;
  year: number;
  icon: string;
  color1: string;
  color2: string;
  descriptionTh: string;
  metaHref: string;
  features: string[];
  status: "active" | "upcoming";
}

export const PLATFORM_GAMES: PlatformGame[] = [
  {
    slug: "pokemon-go",
    nameEn: "Pokémon GO",
    nameTh: "โปเกมอน GO",
    nameShort: "GO",
    platform: "Mobile",
    year: 2016,
    icon: "📍",
    color1: "#0d6efd",
    color2: "#e63946",
    descriptionTh: "เกม AR มือถือ ออกไปจับโปเกมอนในโลกจริง GO Battle League",
    metaHref: "/meta?tab=go",
    features: ["GO Battle League", "Raids", "Community Day", "Special Research"],
    status: "active",
  },
  {
    slug: "pokemon-home",
    nameEn: "Pokémon HOME",
    nameTh: "โปเกมอน HOME",
    nameShort: "HOME",
    platform: "Mobile/Switch",
    year: 2020,
    icon: "🏠",
    color1: "#00b4d8",
    color2: "#48cae4",
    descriptionTh: "ฝากและโอนย้ายโปเกมอนระหว่างทุกเกม Wonder Box & GTS",
    metaHref: "/meta?tab=home",
    features: ["Cross-game transfer", "Wonder Box", "GTS", "Pokémon storage"],
    status: "active",
  },
  {
    slug: "pokemon-champions",
    nameEn: "Pokémon Champions",
    nameTh: "โปเกมอน Champions",
    nameShort: "Champions",
    platform: "Switch/Mobile",
    year: 2025,
    icon: "🏆",
    color1: "#e9c46a",
    color2: "#f4a261",
    descriptionTh: "แพลตฟอร์มการต่อสู้แบบ Competitive อย่างเป็นทางการ",
    metaHref: "/meta?tab=champions",
    features: ["Ranked Battles", "Tournament Mode", "6v6 Standard", "Online Ladder"],
    status: "active",
  },
];
